apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "qc-app.fullname" . }}-pdb
  labels:
    {{- include "qc-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "qc-app.selectorLabels" . | nindent 6 }}