apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qc-app.fullname" . | trunc 63 | trimSuffix "-" }}-secrets
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ required "secrets.jwtSecretKey is required" .Values.secrets.jwtSecretKey | quote }}
  DB_PASSWORD: {{ required "secrets.dbPassword is required" .Values.secrets.dbPassword | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgres:5432/%s" .Values.postgres.username .Values.secrets.dbPassword (include "qc-app.fullname" .) .Values.postgres.database | quote }}
